#!/bin/sh
#ver 1.1.2

_cacheupdate() {
    if [ "$1" == "--force" ] || [ ! -e /tmp/stv_rulecache ]; then
        echo -n "updating rule cache..."
        /sbin/pfctl -vvsr | /usr/local/bin/perl -ne "print if s|^\@([0-9]+).*? label \"(USER_RULE: )?(.*?)\".*$|\1\t\3|p" >/tmp/stv_rulecache
        echo "done"
    fi
}

case $1 in
  --help|-h)
    echo "usage: $(/usr/bin/basename $0) [--cache] [--rule <ruleid>] [filter_regex]"
    exit
    ;;
  --cache)
    _cacheupdate --force
    exit
    ;;
esac

_cacheupdate

if [ "$1" == "--rule" ]; then
    if [ "$2" != "" ]; then
        /usr/bin/egrep "$2" /tmp/stv_rulecache
        exit
    else
        echo "you must specify a search pattern after --rule"
        exit 1
    fi
fi

/sbin/pfctl -vvss >/tmp/stv_statecache

/usr/bin/awk -v m="$1" '
    BEGIN {
        printf("%-14s %-8s %-20s %-26s %-24s %s\n",
        "proto/dir", "iface", "rule", "state/creator", "state", "talkers");
        cnt=0;
    }
    fname != FILENAME {
        fname = FILENAME; idx++
    }
    idx == 1 {
        split($0,a,"\t");
        rid = a[1];
        desc = a[2];
        rules[rid] = desc;
        #printf("added rule %s: %s\n", rid, desc);
        next;
    }
    idx == 2 && !/^ / {
        #print "recno: "NR " <== entrypoint";
        rid=""; sid=""; gw=""; iface=""; talkers="";
        proto=$2; st=$NF;
        i=3; while (i<NF) {
            talkers=sprintf("%s%s ", talkers, $i);
            if($i=="->") { dir="out"; }
            if($i=="<-") { dir="in"; }
            i++;
        }
        proto_dir=sprintf("%s/%s", proto, dir);
        next;
    }
    idx == 2 {
        #print "recno: "NR " -- processing "$0;
        if($0 ~ /\+/) {
            #print "recno: "NR " wscale";
            next;
        }
        if($1=="age") {
            #print "recno: "NR " rule";
            rid=($(NF-1)=="rule") ? sprintf("%s:%s", $NF, substr(rules[$NF], 1, 14)) : "none";
            next;
        }
        if($1=="id:") {
            #print "recno: "NR " id";
            sid=sprintf("%s/%s", $2, $4);
            gw=(($6=="0.0.0.0"||$6=="::") ? "" : sprintf("(via %s)",$6));
            next;
        }
        if($1=="origif:") {
            #print "recno: "NR " origif";
            iface=$2;
        }
    }
    idx == 2 {
        #print "recno: "NR " output";
        mm=sprintf("%%%s%%%s%%%s%%%s%%%s%%%s%%", proto_dir, iface, rid, sid, st, talkers, gw);
        if(mm ~ m) {
            printf "%-14s %-8s %-20s %-26s %-24s %s%s\n",
            proto_dir, iface, rid, sid, st, talkers, gw;
            cnt++;
        }
    }
    END {
        printf("%d state%s\n", cnt, (cnt==1 ? "" : "s"));
    }
    ' /tmp/stv_rulecache /tmp/stv_statecache
